/*
 * Head.java
 * Copyright (c) 2013-2014, SourceTrace Systems, All Rights Reserved.
 *
 * This software is the confidential and proprietary information of SourceTrace Systems
 * ("Confidential Information"). You shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement you entered into with
 * SourceTrace Systems.
 */
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.07 at 04:18:38 PM IST 
//

package com.sourcetrace.eses.txn.schema;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * <p>
 * Java class for Head complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Head">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serialNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="versionNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="agentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="agentToken" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="servPointId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="txnType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="operType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resentCount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="msgNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="batchNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="branchId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tenantId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@ApiModel( value = "Head", description = "Headers of the transaction" )
@XmlType(name = "Head", propOrder = { "serialNo", "versionNo", "agentId", "agentToken", "servPointId", "txnTime",
		"txnType", "operType", "mode", "resentCount", "msgNo", "batchNo", "branchId", "tenantId" })
public class Head implements Serializable {

	@XmlElement(required = true)
	   @ApiModelProperty( value = "Device Serial NO", dataType = "java.lang.String") 
	protected String serialNo;
	@ApiModelProperty( value = "Device Version", dataType = "java.lang.String") 
	@XmlElement(required = true)
	protected String versionNo;
	@ApiModelProperty( value = "Agent Id", dataType = "java.lang.String") 
	@XmlElement(required = true)
	protected String agentId;
	@XmlElement(required = true)
	@ApiModelProperty( value = "Device Version", dataType = "java.lang.String") 

	protected String agentToken;
	@XmlElement(required = true)
	protected String txnTime;
	@XmlElement(required = true)
	protected String txnType;
	protected String servPointId;
	protected String operType;
	protected String resentCount;
	protected String msgNo;
	protected String mode;
	protected String batchNo;
	protected String branchId;
	private String tenantId;

	/**
	 * Gets the serial no.
	 * 
	 * @return the serial no
	 */
	public String getSerialNo() {

		return serialNo;
	}

	/**
	 * Sets the serial no.
	 * 
	 * @param value
	 *            the new serial no
	 */
	public void setSerialNo(String value) {

		this.serialNo = value;
	}

	/**
	 * Gets the version no.
	 * 
	 * @return the version no
	 */
	public String getVersionNo() {

		return versionNo;
	}

	/**
	 * Sets the version no.
	 * 
	 * @param versionNo
	 *            the new version no
	 */
	public void setVersionNo(String versionNo) {

		this.versionNo = versionNo;
	}

	/**
	 * Gets the agent id.
	 * 
	 * @return the agent id
	 */
	public String getAgentId() {

		return agentId;
	}

	/**
	 * Sets the agent id.
	 * 
	 * @param value
	 *            the new agent id
	 */
	public void setAgentId(String value) {

		this.agentId = value;
	}

	/**
	 * Gets the agent token.
	 * 
	 * @return the agent token
	 */
	public String getAgentToken() {

		return agentToken;
	}

	/**
	 * Sets the agent token.
	 * 
	 * @param value
	 *            the new agent token
	 */
	public void setAgentToken(String value) {

		this.agentToken = value;
	}

	/**
	 * Gets the serv point id.
	 * 
	 * @return the serv point id
	 */
	public String getServPointId() {

		return servPointId;
	}

	/**
	 * Sets the serv point id.
	 * 
	 * @param value
	 *            the new serv point id
	 */
	public void setServPointId(String value) {

		this.servPointId = value;
	}

	/**
	 * Gets the txn type.
	 * 
	 * @return the txn type
	 */

	/**
	 * Gets the value of the txnType property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getTxnType() {

		return txnType;
	}

	/**
	 * Sets the txn type.
	 * 
	 * @param value
	 *            the new txn type
	 */
	public void setTxnType(String value) {

		this.txnType = value;
	}

	/**
	 * Gets the oper type.
	 * 
	 * @return the oper type
	 */
	public String getOperType() {

		return operType;
	}

	/**
	 * Sets the oper type.
	 * 
	 * @param value
	 *            the new oper type
	 */
	public void setOperType(String value) {

		this.operType = value;
	}

	/**
	 * Gets the resent count.
	 * 
	 * @return the resent count
	 */
	public String getResentCount() {

		return resentCount;
	}

	/**
	 * Sets the resent count.
	 * 
	 * @param value
	 *            the new resent count
	 */
	public void setResentCount(String value) {

		this.resentCount = value;
	}

	/**
	 * Gets the msg no.
	 * 
	 * @return the msg no
	 */
	public String getMsgNo() {

		return msgNo;
	}

	/**
	 * Sets the msg no.
	 * 
	 * @param value
	 *            the new msg no
	 */
	public void setMsgNo(String value) {

		this.msgNo = value;
	}

	/**
	 * Gets the txn time.
	 * 
	 * @return the txn time
	 */
	public String getTxnTime() {

		return txnTime;
	}

	/**
	 * Sets the txn time.
	 * 
	 * @param txnTime
	 *            the new txn time
	 */
	public void setTxnTime(String txnTime) {

		this.txnTime = txnTime;
	}

	/**
	 * Gets the mode.
	 * 
	 * @return the mode
	 */
	public String getMode() {

		return mode;
	}

	/**
	 * Sets the mode.
	 * 
	 * @param mode
	 *            the new mode
	 */
	public void setMode(String mode) {

		this.mode = mode;
	}

	/**
	 * Gets the batch no.
	 * 
	 * @return the batch no
	 */
	public String getBatchNo() {

		return batchNo;
	}

	/**
	 * Sets the batch no.
	 * 
	 * @param batchNo
	 *            the new batch no
	 */
	public void setBatchNo(String batchNo) {

		this.batchNo = batchNo;
	}

	public String getBranchId() {
		return branchId;
	}

	public void setBranchId(String branchId) {
		this.branchId = branchId;
	}

	public String getTenantId() {
		return tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

}
